# live display
fps: 8

precision: double

nx: 32
ny: 16

eps: '0.1'
alpha: '0.0'
beta: '0.0'

na: -1
nb: 1

dt: '1e-3'

fftw_wisdoms:
  - '/home/mike/Data/labdata/FFT/turnbull2/4096x32_246.pkl'
  - '/home/mike/Data/labdata/FFT/turnbull2/32x16_1246.pkl'

# liquid solid small field minimization
base:
  n_steps: 31

  target: 'psibar'
  tol: '1e-13'
  patience: 400

  refresh_interval: 4

  fft_threads: 1
  wisdom_only: true


# liquid solid interface long field minimization
long:
  mx: 128
  my: 2
  width0: 40

  n_steps: 31
  
  target: 'F'
  tol: '1e-14'
  patience: 100

  refresh_interval: 1

  fft_threads: 4
  wisdom_only: true


